#!/usr/bin/env bash
# Builds throwaway repositories with real git and writes what git-nudge parses
# to tests/fixtures.ts. Run it again when git's output may have changed:
#   bash mods/git-nudge/tests/make-fixtures.sh
# Needs git and node. Dates, names and the default branch are fixed, so the
# output (commit ids included) is the same on every run.
set -euo pipefail

HERE=$(cd "$(dirname "$0")" && pwd)
ROOT=$(mktemp -d)
OUT="$ROOT/out"
mkdir -p "$OUT"
trap 'rm -rf "$ROOT"' EXIT

export GIT_CONFIG_GLOBAL=/dev/null GIT_CONFIG_NOSYSTEM=1
export GIT_AUTHOR_NAME=fx GIT_AUTHOR_EMAIL=fx@example.com GIT_COMMITTER_NAME=fx GIT_COMMITTER_EMAIL=fx@example.com
export GIT_AUTHOR_DATE='2026-01-01T00:00:00Z' GIT_COMMITTER_DATE='2026-01-01T00:00:00Z'
G() { git -c init.defaultBranch=main -c core.autocrlf=false "$@"; }

# Absolute paths differ per machine: write them as /fx.
ROOT_W=$(cd "$ROOT" && (pwd -W 2>/dev/null || pwd))
save() { sed -e "s#$ROOT_W#/fx#g" -e "s#$ROOT#/fx#g" > "$OUT/$1.txt"; }

cd "$ROOT"
G init -q --bare remote.git
G clone -q remote.git a 2>/dev/null
cd a
echo one > f.txt && G add f.txt && G commit -qm one && G push -q origin main
cd .. && G clone -q remote.git b && cd a

G status --porcelain=v2 --branch | save status-insync

# behind: b pushes two commits, a fetches
(cd ../b && echo two >> f.txt && G commit -qam two && echo three >> f.txt && G commit -qam three && G push -q origin main)
G fetch -q
G status --porcelain=v2 --branch | save status-behind

# diverged: a commits while behind
echo local > g.txt && G add g.txt && G commit -qm local
G status --porcelain=v2 --branch | save status-diverged
G reset -q --hard origin/main

# ahead
echo four >> f.txt && G commit -qam four
G status --porcelain=v2 --branch | save status-ahead
G push -q origin main

# dirty: one unstaged, one staged, one untracked
echo staged > s.txt && G add s.txt
echo changed >> f.txt
echo new > u.txt
G status --porcelain=v2 --branch | save status-dirty

# two stashes, made 2026-01-01 and 2026-01-05
G stash -q -u
echo again >> f.txt && GIT_COMMITTER_DATE='2026-01-05T00:00:00Z' G stash -q
G stash list --format=%ct | save stash
G stash clear

# a merge stopped on a conflict
G switch -q -c side && echo side > f.txt && G commit -qam side
G switch -q main && echo mainline > f.txt && G commit -qam mainline
G merge -q side >/dev/null 2>&1 || true
G status --porcelain=v2 --branch | save status-conflict
G merge --abort
G reset -q --hard origin/main && G branch -q -D side

# detached HEAD
G switch -q --detach HEAD
G status --porcelain=v2 --branch | save status-detached
G switch -q main

# a branch with no upstream
G switch -q -c local-only
G status --porcelain=v2 --branch | save status-noupstream
G switch -q main && G branch -q -D local-only

# feat-merged: merged, then deleted on the remote; feat-squash: squashed, then
# deleted; feat-open: still on the remote; feat-wt: deleted, checked out in
# another worktree; wt-gone-branch: in a worktree whose directory is gone.
for b in feat-merged feat-squash feat-open feat-wt; do
  G switch -q -c "$b" main && echo "$b" > "$b.txt" && G add "$b.txt" && G commit -qm "$b" && G push -q -u origin "$b"
done
G switch -q main
G merge -q --no-edit feat-merged
G merge -q --squash feat-squash >/dev/null && G commit -qm 'squash feat-squash'
G push -q origin main
G worktree add -q ../wt feat-wt
G worktree add -q ../wt-gone -b wt-gone-branch
rm -rf ../wt-gone
# Deleted on the remote by someone else, as a merged pull request is: a keeps
# its remote-tracking refs until it prunes.
(cd ../b && G push -q origin --delete feat-merged feat-squash feat-wt)
G fetch -q
G status --porcelain=v2 --branch | save status-main-after-merge

G ls-remote --heads origin | save ls-remote
G for-each-ref --format='%(refname:short)%09%(objectname)%09%(upstream:remotename)%09%(upstream:remoteref)%09%(worktreepath)' refs/heads | save branches
G for-each-ref --merged HEAD --format='%(refname:short)' refs/heads | save merged
G worktree list --porcelain | save worktrees

# on a branch whose upstream is gone: before and after a prune
G switch -q feat-merged
G status --porcelain=v2 --branch | save status-gone-noprune
G fetch -q --prune
G status --porcelain=v2 --branch | save status-gone-pruned
G switch -q main

# an unborn repository
cd "$ROOT" && G init -q empty && cd empty
G status --porcelain=v2 --branch | save status-initial

# settings as git prints them back (keys come back lowercased)
G config git-nudge.fetchInterval 0
G config git-nudge.tellClaude no
G config git-nudge.band maybe
G config git-nudge.stashAgeDays x7
G config git-nudge.fetchIntervall 3
G config --get-regexp '^git-nudge\.' | save config

git version | save version

{
  echo '// Generated by tests/make-fixtures.sh from real git. Do not edit: run the script again.'
  echo 'export const FIXTURES = {'
  for f in "$OUT"/*.txt; do
    printf "  '%s': %s,\n" "$(basename "$f" .txt)" \
      "$(node -e 'process.stdout.write(JSON.stringify(require("fs").readFileSync(process.argv[1], "utf8")))' "$f")"
  done
  echo '} as const'
} > "$HERE/fixtures.ts"
echo "wrote $HERE/fixtures.ts"
